apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
      annotations:
        prometheus.io/scrape: "false"
        prometheus.io/port: "8888"
    spec:
      serviceAccountName: otel-collector
      tolerations:
      - operator: Exists
      containers:
      - name: otel-collector
        image: harbor.k8s.local/dockerhub-cache/otel/opentelemetry-collector-contrib:0.145.0
        args:
          - '--config=file:/etc/otelcol/otel-base-config.yaml'
          - '--config=file:/etc/otelcol/otel-metrics-pipeline.yaml'
          - '--config=file:/etc/otelcol/otel-kubeletstats-pipeline.yaml'
          - '--config=file:/etc/otelcol/otel-logs-pipeline.yaml'
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 8888
          name: metrics
        - containerPort: 8889
          name: prom-exporter
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otelcol/
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 10
          periodSeconds: 15
      volumes:
      - name: otel-collector-config
        projected:
          sources:
          - configMap:
              name: otel-base-config
          - configMap:
              name: otel-metrics-pipeline
          - configMap:
              name: otel-kubeletstats-pipeline
          - configMap:
              name: otel-logs-pipeline
      - name: varlogpods
        hostPath:
          path: /var/log/pods
