apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: otel-base-config
    files:
      - otel-base-config.yaml
    options:
      immutable: true
  - name: otel-metrics-pipeline
    files:
      - otel-metrics-pipeline.yaml
    options:
      immutable: true
