apiVersion: 1
datasources:
  - name: Thanos
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://thanos-query.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 10s
