- name: test ansible runner
  hosts: localhost
  become: false
  gather_facts: true
  roles:
    - test_ansible_runner
    - setup_localhost

- name: provision infrastructure
  hosts: proxmox
  gather_facts: false
  become: true
  strategy: free
  roles:
    - provision_infra

- name: setup k8s cluster master nodes
  hosts: k8s-control
  gather_facts: false
  become: true
  roles:
    - setup_cluster_master

- name: setup k8s cluster worker nodes
  hosts: k8s-nodes
  gather_facts: true
  become: true
  roles:
    - setup_cluster_node

- name: setup cillium networking
  hosts: k8s
  gather_facts: false
  become: true
  roles:
    - bootstrap_cillium

- name: setup storage classes
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - bootstrap_cephfs_storage_class

- name: setup argo cd
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - bootstrap_argocd

- name: setup applications
  hosts: localhost
  gather_facts: false
  become: true
  roles:
    - bootstrap_applications
  