apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - auth-delegator-clusterrolebinding.yaml
  - auth-reader-rolebinding.yaml
  - deployment.yaml
  - service.yaml
  - apiservice.yaml
