apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: loki
spec:
  clusterSelector:
    matchLabels:
      cluster: homelab
  syncMode: Continuous
  dependsOn:
    - harbor
  policyRefs:
    - kind: ConfigMap
      name: sveltos-app-loki
      namespace: projectsveltos
      deploymentType: Remote
