apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: thanos
spec:
  clusterSelector:
    matchLabels:
      cluster: homelab
  syncMode: Continuous
  dependsOn:
    - rook-ceph-cluster  # S3 bucket + block PVCs
    - otel-collector     # remote-write source
    - harbor
  policyRefs:
    - kind: ConfigMap
      name: sveltos-app-thanos
      namespace: projectsveltos
      deploymentType: Remote
