apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: "https://argocd.k8s.local"
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.k8s.local/realms/homelab
    clientID: argocd
    clientSecret: argocd-keycloak-secret
    requestedScopes:
      - openid
      - profile
      - email
      - roles
    rootCA: ""
    insecureSkipTLSVerify: true
