
proxmox:
  hosts:
    k8s-control-1:
      ansible_host: '{{ lookup("env", "K8S_CONTROL_1_IP") }}'
      vm_provision:
        cpu: '{{ lookup("env", "K8S_CONTROL_1_CPU") | default("2") }}'
        memory_mb: '{{ lookup("env", "K8S_CONTROL_1_MEM_MB") | default("4096") }}'
        disk_gb: '{{ lookup("env", "K8S_CONTROL_1_DISK_GB") | default("20") }}'
        ip: '{{ lookup("env", "K8S_CONTROL_1_IP") }}'
        ssh_user: '{{ lookup("env", "K8S_SSH_USER") }}'
        ssh_key: '{{ lookup("env", "K8S_SSH_KEY") }}'
      labels:
        role: main-control
    k8s-node-1:
      ansible_host: '{{ lookup("env", "K8S_NODE_1_IP") }}'
      vm_provision:
        cpu: '{{ lookup("env", "K8S_NODE_1_CPU") | default("2") }}'
        memory_mb: '{{ lookup("env", "K8S_NODE_1_MEM_MB") | default("4096") }}'
        disk_gb: '{{ lookup("env", "K8S_NODE_1_DISK_GB") | default("20") }}'
        ip: '{{ lookup("env", "K8S_NODE_1_IP") }}'
        ssh_user: '{{ lookup("env", "K8S_SSH_USER") }}'
        ssh_key: '{{ lookup("env", "K8S_SSH_KEY") }}'
      labels:
        role: main-node
        compute: cuda
  vars:
    labels:
      infra: proxmox
bare-metal:
  hosts: {}
  vars:
    labels:
      infra: baremetal
k8s:
  children:
    k8s-control:
      hosts:
        k8s-control-1:
          ansible_host: '{{ lookup("env", "K8S_CONTROL_1_IP") }}'
    k8s-nodes:
      hosts:
        k8s-node-1:
          ansible_host: '{{ lookup("env", "K8S_NODE_1_IP") }}'
  vars:
    K8S_VERSION: '{{ lookup("env", "K8S_VERSION") | default("1.34") }}'
    CRIO_VERSION: '{{ lookup("env", "CRIO_VERSION") | default("1.33") }}'
    CILIUM_VERSION: '{{ lookup("env", "CILIUM_VERSION") | default("1.18.1") }}'
    CILIUM_LOADBALANCER_IPPOOL: '{{ lookup("env", "CILIUM_LOADBALANCER_IPPOOL") }}'
    ENABLE_GATEWAY_API: '{{ lookup("env", "ENABLE_GATEWAY_API") | default("False") }}'
    ENABLE_CEPH: '{{ lookup("env", "ENABLE_CEPH") | default("false") }}'
    ENABLE_CUDA: '{{ lookup("env", "ENABLE_CUDA") | default("false") }}'
    ENABLE_ISTIO: '{{ lookup("env", "ENABLE_ISTIO") | default("false") }}'
    NVIDIA_DEVICE_PLUGIN_VERSION: '{{ lookup("env", "NVIDIA_DEVICE_PLUGIN_VERSION") | default("v0.14.5") }}'
    ansible_user: '{{ lookup("env", "K8S_SSH_USER") | default(ansible_user_id) }}'
    ansible_ssh_private_key_file: '{{ lookup("env", "K8S_SSH_KEY") | default("~/.ssh/id_rsa") }}'
    ansible_ssh_public_key_file: '{{ lookup("env", "K8S_SSH_PUB_KEY") | default("~/.ssh/id_rsa.pub") }}'
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh

