all: 
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: '{{ playbook_dir }}/.venv/bin/python'
      K8S_VERSION: '{{ lookup("env", "K8S_VERSION") | default("1.34") }}'
      ARGOCD_VERSION: '{{ lookup("env", "ARGOCD_VERSION") | default("3.1.7") }}'
      REPOSITORY_SSH_URL: '{{ lookup("env", "REPOSITORY_SSH_URL") }}'
      REPOSITORY_TOKEN: '{{ lookup("env", "REPOSITORY_TOKEN") }}'
  vars:
    ubuntu_release_version: '{{ lookup("env", "UBUNTU_RELEASE_VERSION") | default("24.04.3") }}'
    proxmox_api_user: '{{ lookup("env", "PROXMOX_API_USER") }}'
    proxmox_api_password: '{{ lookup("env", "PROXMOX_API_PASSWORD") }}'
    proxmox_api_host: '{{ lookup("env", "PROXMOX_API_HOST") }}'
    proxmox_node: '{{ lookup("env", "PROXMOX_NODE") }}'
    proxmox_local_storage: '{{ lookup("env", "PROXMOX_LOCAL_STORAGE") }}'
    proxmox_storage: '{{ lookup("env", "PROXMOX_STORAGE") | default("local-lvm") }}'
    vm_gateway: '{{ lookup("env", "VM_GATEWAY") }}'
    vm_nameserver: '{{ lookup("env", "VM_NAMESERVER") }}'