apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: monitoring
  labels:
    app: loki
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    ingress.cilium.io/force-https: "enabled"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - loki.k8s.local
    secretName: loki-tls
  rules:
  - host: loki.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki
            port:
              number: 3100
