- name: endforce iso images exist on proxmox
  ansible.builtin.import_role:
    name: provision_infra
    tasks_from: handle_iso
  delegate_to: localhost
  run_once: true

- name: create proxmox vms
  ansible.builtin.import_role:
    name: provision_infra
    tasks_from: create_vm