apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - serviceaccount.yaml
  - objectbucketclaim.yaml
  - objstore-config-template.yaml
  - thanos-receive-statefulset.yaml
  - thanos-receive-service.yaml
  - thanos-query-deployment.yaml
  - thanos-query-service.yaml
  - thanos-query-ingress.yaml
  - thanos-store-statefulset.yaml
  - thanos-store-service.yaml
  - thanos-compactor-statefulset.yaml
  - thanos-compactor-service.yaml
  - thanos-ruler-statefulset.yaml
  - thanos-ruler-service.yaml

configMapGenerator:
  - name: thanos-ruler-alert-rules
    files:
      - thanos-ruler-alert-rules.yaml
    options:
      immutable: true
