apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: security
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      serviceAccountName: keycloak
      tolerations:
      - key: role
        operator: Equal
        value: infra
        effect: NoSchedule
      containers:
      - name: keycloak
        image: harbor.k8s.local/quay-cache/keycloak/keycloak:26.5.3
        args: ["start", "--import-realm"]
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          valueFrom:
            secretKeyRef:
              name: keycloak-db-app
              key: host
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              name: keycloak-db-app
              key: dbname
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-db-app
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-db-app
              key: password
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: "https://keycloak.k8s.local"
        - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
          value: "true"
        - name: KC_HEALTH_ENABLED
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9000
        startupProbe:
          httpGet:
            path: /health/started
            port: 9000
          periodSeconds: 5
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9000
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
        volumeMounts:
        - name: realm-config
          mountPath: /opt/keycloak/data/import
          readOnly: true
      volumes:
      - name: realm-config
        configMap:
          name: keycloak-realm-homelab
