- name: download {{ REPO }} gpg key
  ansible.builtin.get_url:
    url: "{{ REPO_KEY_URL}}"
    dest: "{{ REPO_KEY_PATH }}"
    mode: '0644'
    force: true
  become: true
  retries: 5
  delay: 10
  register: gpg_key_result
  until: gpg_key_result is success

- name: add {{ REPO }} repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ REPO_KEY_PATH }}] {{ REPO_STRING }}"
    filename: "{{ REPO_FILE_PATH }}"
    state: present
  become: true

- name: apt install {{ REPO }}
  ansible.builtin.apt:
    pkg:
    - "{{ REPO }}"
    state: present
    update_cache: yes
  become: true
  retries: 5
  delay: 10
  register: apt_install_result
  until: apt_install_result is success

- name: apt-mark hold {{ REPO }}
  ansible.builtin.dpkg_selections:
    name: "{{ REPO }}"
    selection: hold
  become: true