apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-ingress
  namespace: monitoring
  labels:
    app: matrix
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    ingress.cilium.io/force-https: "enabled"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - matrix.k8s.local
    secretName: matrix-tls
  rules:
  - host: matrix.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: matrix
            port:
              number: 8008
