apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - rbac.yaml
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - bootstrap-job.yaml

configMapGenerator:
  - name: matrix-oidc-config
    files:
      - synapse-oidc.yaml
    options:
      labels:
        app: matrix
