apiVersion: v1
kind: ServiceAccount
metadata:
  name: matrix
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: matrix-secret-manager
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
  resourceNames: ["matrix-db", "matrix-bot", "matrix-admin", "matrix-registration"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: matrix-secret-manager
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: matrix
  namespace: monitoring
roleRef:
  kind: Role
  name: matrix-secret-manager
  apiGroup: rbac.authorization.k8s.io
