apiVersion: batch/v1
kind: Job
metadata:
  name: matrix-init-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: matrix
      restartPolicy: OnFailure
      containers:
      - name: generate-secrets
        image: alpine:3.19
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache openssl kubectl
          
          # Generate database password if secret doesn't exist
          if kubectl get secret matrix-db -n monitoring &>/dev/null; then
            echo "Database secret already exists"
          else
            DB_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
            kubectl create secret generic matrix-db \
              --from-literal=username="synapse" \
              --from-literal=password="$DB_PASSWORD" \
              --from-literal=database="synapse" \
              --from-literal=postgres-password="$DB_PASSWORD" \
              -n monitoring
            echo "Created database secret"
          fi
          
          echo "Secrets initialized. Retrieve with:"
          echo "  DB: kubectl get secret matrix-db -n monitoring -o jsonpath='{.data.password}' | base64 -d"
