apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-bridge
  namespace: argocd
  labels:
    category: monitoring
spec:
  project: homelab
  source:
    repoURL: git@gitlab.com:dsynapalos/cluster-setup.git
    targetRevision: main
    path: argocd_applications/monitoring/matrix-bridge
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
