apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

resources:
  - rbac.yaml
  - bootstrap-job.yaml
  - artifact-indexer-cronjob.yaml
  - cve-reporter-cronjob.yaml

configMapGenerator:
  - name: cve-reporter
    files:
      - cve-reporter.py
    options:
      disableNameSuffixHash: true
