apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: harbor-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  sources:
    - secret:
        name: homelab-ca-secret
        key: ca.crt
  target:
    secret:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: harbor
