- name: enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

- name: allow k8s control ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  loop:
    - 22
    - 4240
    - 4244:4245
    - 4250
    - 6443
    - 2379:2380
    - 10250
    - 10257
    - 10259
  when: inventory_hostname == 'k8s-control-1'

- name: allow cilium vxlan and wireguard on control plane
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    state: enabled
  loop:
    - 8472     # VXLAN tunnel
    - 51871    # WireGuard

- name: allow k8s node ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443
    - 4240
    - 4244:4245
    - 4250
    - 10250
    - 10256
  when: inventory_hostname in groups['k8s-nodes']

- name: allow k8s node tcp/udp ports
  community.general.ufw:
    rule: allow
    port: 30000:32767
    proto: "{{ item }}"
    state: enabled
  loop:
    - tcp
    - udp
  when: inventory_hostname in groups['k8s-nodes']