- name: upgrade all packages
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes

- name: apt install prerequisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: latest
    update_cache: yes