- name: upgrade all packages
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes
  retries: 5
  delay: 10
  register: apt_upgrade_result
  until: apt_upgrade_result is success

- name: apt install prerequisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: latest
    update_cache: yes
  retries: 5
  delay: 10
  register: apt_prereqs_result
  until: apt_prereqs_result is success