apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

resources:
  - cluster.yaml
  - blockpool.yaml
  - filesystem.yaml
  - object-store.yaml
  - rook-config-override.yaml

