# Allows cert-manager components to schedule on infra-tainted nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      tolerations:
      - key: role
        operator: Equal
        value: infra
        effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  template:
    spec:
      tolerations:
      - key: role
        operator: Equal
        value: infra
        effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  template:
    spec:
      tolerations:
      - key: role
        operator: Equal
        value: infra
        effect: NoSchedule
